server:
  port: 65000
  diff:
    negative: -20
    positive: 40
dispatcher:
  -
    type: 'mssql'
    format: 'human'
    user: 'seg'
    password: 'Dnl123'
    database: 'Bb_datos'
    server: '190.13.132.109'
    port: 1433
